source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/cicadajz/cicada.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CicadaSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CicadaSwiftDemo
pod 'Alamofire', '~> 5.6.0'
pod 'SwiftyJSON', '~> 5.0.1'
pod 'Kingfisher', '~> 7.2.1'
pod 'SnapKit', '~> 5.6.0'
pod 'MonkeyKing', '~> 2.2.1'
pod 'Dollar'
pod 'R.swift'
pod 'RxSwift', '~> 6.5.0'
pod 'RxCocoa', '~> 6.5.0'
pod 'RxDataSources', '~> 5.0.0'
pod 'CocoaAsyncSocket', '~> 7.6.5'
pod 'SwiftProtobuf', '~> 1.19.0'
pod 'CicadaPodTest', '~> 0.2.0'

  target 'CicadaSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CicadaSwiftDemoUITests' do
    # Pods for testing
  end

end
